### ISSUE TITLE
Fatal error in iOS 15.3 and below

### ISSUE THREAD

**Issue by power-media** [JBtje/vite-vue3pdf#3]
Hi
I have an issue that occurs in browsers in iOS devices (Safari and WebViews), version iOS 15.3 and lower.

`TypeError: Ee.split("+").at is not a function. (In 'Ee.split("+").at(-1)', 'Ee.split("+").at' is undefined)`

That breaks all other scripts execution.

     - vue3pdf version: 0.2.0
     - vue.js version: 3.2.45
     - vite version: 4.0.0
     - browser version: 15.3 (same a iOS version I guess)
     - OS version: iOS 15.3 and lower
     
Any chance for quick fix? I tried to go over it but no luck so far, and my deadline for it is just now.
Thanks in advance!

**Comment by JBtje** [comment]
Hi there,

Please provide a repository with minimal code in which the problem is present. I'm using this repo in multiple projects, but have not seen this error. Also make sure you have the correct version of pdf.worker.js

**Comment by power-media** [comment]
Hi
I've done this now.

Repository: https://github.com/power-media/vite-vue3pdf-iOSerror
Running example: https://vite-vue3pdf-i-o-serror.vercel.app/

I debugged it on iOS14 - the error I mentioned above occurs and prevents app rendering.
I have separated vendor chunk in build (see vite config) for clarity that the error comes from libraries.

That is ONLY iOS issue - I didn't see any problems on Desktop Safari.
Looking forward to your feedback.

**Comment by JBtje** [comment]
Below solution I emailed the 24th of may, I assume the problem to be resolved since i haven't heard since.
-------------------------
The problem at hand:
https://caniuse.com/?search=Array.prototype.at

array.protorype.at is not supported for iOS 15.3 and below, hence the error.

A polyfill would most likely be the solution.
Since pdf.worker.js is not part of the package, you can add the polyfill yourself to the pdf.worker.js and hopefully that will solve the problem.
https://github.com/qutebrowser/qutebrowser/issues/7335#issuecomment-1213153686

If that works, I might be able to add the polyfill by default in the project, so it doesn’t modification of the pdf.worker.js

**Comment by power-media** [comment]
Hi
Apologies for not coming back to you.
Adding a polyfill was indeed the solution that helped to resolve the errors.
I needed to add it to both this project as well as to the pdf.worker.js.

Thank you for yous support!
